# Generated by Django 3.1.2 on 2020-10-22 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubeSection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubesection',
            name='videoLength',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='youtubesection',
            name='videoimage',
            field=models.CharField(blank=True, default='default.jpg', max_length=1000),
        ),
    ]
